---
title: "Research"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float: yes
    theme: yeti
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = F)
knitr::opts_chunk$set(message = F)
## For more inspiration on customizing the html output, refer to the following:
# https://bookdown.org/yihui/rmarkdown/html-document.html#table-of-contents
```


<style>
body {text-align: left}
</style>

___

## 1. Individual differences in foraging behavior of Argentine ants (_Linepithema humile_)

Argentine ant foragers vary in their propensity to explore novel environments. We found that individuals who wander off of established forging trails to find novel food resources are more exploratory. If you are interested in learning more see Madrzyk and Pinter-Wollman, 2022.

___

## 2. Ant community dynamics in disturbed and natural habitats

Data collected in 2012 around Stanford campus and Jasper Ridge Biological Preserve shows differences in species ability to occupy and persist at food food baits over time. Notably, we find that in areas that have been subjected to intermediate levels of human disturbance, only Winter and Argentine ants are present. In addition, these two species show a similar ability to occupy and persist at food sources over time. 

___

## 3. Native and invasive species interactions

> **How do native Winter ants (_Prenolepis imparis_) coexisit with invasive Argentine Ants (_Linepithema humile_)**

Using oak trees around Stanford campus, me and a team in Stanford undergraduates have been monitoring foraging behavior of Winter and Argentine ants over the course of the year to see how they respond to one another.

___

## Other Work

 * Worked on Dr. Deborah Gordon's long-term field study on how harvester ants (_Pogonomyrmex barbatus_) respond to climate change.
 * Working with Dr. Katie Fiocca to determine how isolation in harvester ants (_Pogonomyrmex barbatus_) changes their cuticular hydrocarbons.